# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/destoer/projects/interloper

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/destoer/projects/interloper

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/destoer/projects/interloper/CMakeFiles /home/destoer/projects/interloper//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/destoer/projects/interloper/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named interloper

# Build rule for target.
interloper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 interloper
.PHONY : interloper

# fast build rule for target.
interloper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/build
.PHONY : interloper/fast

src/expression.o: src/expression.cpp.o
.PHONY : src/expression.o

# target to build an object file
src/expression.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/expression.cpp.o
.PHONY : src/expression.cpp.o

src/expression.i: src/expression.cpp.i
.PHONY : src/expression.i

# target to preprocess a source file
src/expression.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/expression.cpp.i
.PHONY : src/expression.cpp.i

src/expression.s: src/expression.cpp.s
.PHONY : src/expression.s

# target to generate assembly for a file
src/expression.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/expression.cpp.s
.PHONY : src/expression.cpp.s

src/immediate.o: src/immediate.cpp.o
.PHONY : src/immediate.o

# target to build an object file
src/immediate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/immediate.cpp.o
.PHONY : src/immediate.cpp.o

src/immediate.i: src/immediate.cpp.i
.PHONY : src/immediate.i

# target to preprocess a source file
src/immediate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/immediate.cpp.i
.PHONY : src/immediate.cpp.i

src/immediate.s: src/immediate.cpp.s
.PHONY : src/immediate.s

# target to generate assembly for a file
src/immediate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/immediate.cpp.s
.PHONY : src/immediate.cpp.s

src/interloper.o: src/interloper.cpp.o
.PHONY : src/interloper.o

# target to build an object file
src/interloper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/interloper.cpp.o
.PHONY : src/interloper.cpp.o

src/interloper.i: src/interloper.cpp.i
.PHONY : src/interloper.i

# target to preprocess a source file
src/interloper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/interloper.cpp.i
.PHONY : src/interloper.cpp.i

src/interloper.s: src/interloper.cpp.s
.PHONY : src/interloper.s

# target to generate assembly for a file
src/interloper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/interloper.cpp.s
.PHONY : src/interloper.cpp.s

src/interpretter.o: src/interpretter.cpp.o
.PHONY : src/interpretter.o

# target to build an object file
src/interpretter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/interpretter.cpp.o
.PHONY : src/interpretter.cpp.o

src/interpretter.i: src/interpretter.cpp.i
.PHONY : src/interpretter.i

# target to preprocess a source file
src/interpretter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/interpretter.cpp.i
.PHONY : src/interpretter.cpp.i

src/interpretter.s: src/interpretter.cpp.s
.PHONY : src/interpretter.s

# target to generate assembly for a file
src/interpretter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/interpretter.cpp.s
.PHONY : src/interpretter.cpp.s

src/ir.o: src/ir.cpp.o
.PHONY : src/ir.o

# target to build an object file
src/ir.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/ir.cpp.o
.PHONY : src/ir.cpp.o

src/ir.i: src/ir.cpp.i
.PHONY : src/ir.i

# target to preprocess a source file
src/ir.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/ir.cpp.i
.PHONY : src/ir.cpp.i

src/ir.s: src/ir.cpp.s
.PHONY : src/ir.s

# target to generate assembly for a file
src/ir.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/ir.cpp.s
.PHONY : src/ir.cpp.s

src/lexer.o: src/lexer.cpp.o
.PHONY : src/lexer.o

# target to build an object file
src/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/lexer.cpp.o
.PHONY : src/lexer.cpp.o

src/lexer.i: src/lexer.cpp.i
.PHONY : src/lexer.i

# target to preprocess a source file
src/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/lexer.cpp.i
.PHONY : src/lexer.cpp.i

src/lexer.s: src/lexer.cpp.s
.PHONY : src/lexer.s

# target to generate assembly for a file
src/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/lexer.cpp.s
.PHONY : src/lexer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/optimize.o: src/optimize.cpp.o
.PHONY : src/optimize.o

# target to build an object file
src/optimize.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/optimize.cpp.o
.PHONY : src/optimize.cpp.o

src/optimize.i: src/optimize.cpp.i
.PHONY : src/optimize.i

# target to preprocess a source file
src/optimize.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/optimize.cpp.i
.PHONY : src/optimize.cpp.i

src/optimize.s: src/optimize.cpp.s
.PHONY : src/optimize.s

# target to generate assembly for a file
src/optimize.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/optimize.cpp.s
.PHONY : src/optimize.cpp.s

src/parser.o: src/parser.cpp.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/test/expr.o: src/test/expr.cpp.o
.PHONY : src/test/expr.o

# target to build an object file
src/test/expr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/test/expr.cpp.o
.PHONY : src/test/expr.cpp.o

src/test/expr.i: src/test/expr.cpp.i
.PHONY : src/test/expr.i

# target to preprocess a source file
src/test/expr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/test/expr.cpp.i
.PHONY : src/test/expr.cpp.i

src/test/expr.s: src/test/expr.cpp.s
.PHONY : src/test/expr.s

# target to generate assembly for a file
src/test/expr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/test/expr.cpp.s
.PHONY : src/test/expr.cpp.s

src/test/lexer_test.o: src/test/lexer_test.cpp.o
.PHONY : src/test/lexer_test.o

# target to build an object file
src/test/lexer_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/test/lexer_test.cpp.o
.PHONY : src/test/lexer_test.cpp.o

src/test/lexer_test.i: src/test/lexer_test.cpp.i
.PHONY : src/test/lexer_test.i

# target to preprocess a source file
src/test/lexer_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/test/lexer_test.cpp.i
.PHONY : src/test/lexer_test.cpp.i

src/test/lexer_test.s: src/test/lexer_test.cpp.s
.PHONY : src/test/lexer_test.s

# target to generate assembly for a file
src/test/lexer_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/test/lexer_test.cpp.s
.PHONY : src/test/lexer_test.cpp.s

src/test/test.o: src/test/test.cpp.o
.PHONY : src/test/test.o

# target to build an object file
src/test/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/test/test.cpp.o
.PHONY : src/test/test.cpp.o

src/test/test.i: src/test/test.cpp.i
.PHONY : src/test/test.i

# target to preprocess a source file
src/test/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/test/test.cpp.i
.PHONY : src/test/test.cpp.i

src/test/test.s: src/test/test.cpp.s
.PHONY : src/test/test.s

# target to generate assembly for a file
src/test/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/test/test.cpp.s
.PHONY : src/test/test.cpp.s

src/type.o: src/type.cpp.o
.PHONY : src/type.o

# target to build an object file
src/type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/type.cpp.o
.PHONY : src/type.cpp.o

src/type.i: src/type.cpp.i
.PHONY : src/type.i

# target to preprocess a source file
src/type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/type.cpp.i
.PHONY : src/type.cpp.i

src/type.s: src/type.cpp.s
.PHONY : src/type.s

# target to generate assembly for a file
src/type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interloper.dir/build.make CMakeFiles/interloper.dir/src/type.cpp.s
.PHONY : src/type.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... interloper"
	@echo "... src/expression.o"
	@echo "... src/expression.i"
	@echo "... src/expression.s"
	@echo "... src/immediate.o"
	@echo "... src/immediate.i"
	@echo "... src/immediate.s"
	@echo "... src/interloper.o"
	@echo "... src/interloper.i"
	@echo "... src/interloper.s"
	@echo "... src/interpretter.o"
	@echo "... src/interpretter.i"
	@echo "... src/interpretter.s"
	@echo "... src/ir.o"
	@echo "... src/ir.i"
	@echo "... src/ir.s"
	@echo "... src/lexer.o"
	@echo "... src/lexer.i"
	@echo "... src/lexer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/optimize.o"
	@echo "... src/optimize.i"
	@echo "... src/optimize.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/test/expr.o"
	@echo "... src/test/expr.i"
	@echo "... src/test/expr.s"
	@echo "... src/test/lexer_test.o"
	@echo "... src/test/lexer_test.i"
	@echo "... src/test/lexer_test.s"
	@echo "... src/test/test.o"
	@echo "... src/test/test.i"
	@echo "... src/test/test.s"
	@echo "... src/type.o"
	@echo "... src/type.i"
	@echo "... src/type.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

